### ISSUE TITLE
Support for password-managers

### ISSUE THREAD

**Issue by LarsK1** [invoiceninja/admin-portal#334]
Hey there,
is it possible to add the necessary html-fields to the login/registration-fields in a manner, that password managers are able to auto fill or save the common fields?

See her, which fields would be required: [https://hiddedevries.nl/en/blog/2018-01-13-making-password-managers-play-ball-with-your-login-form](https://hiddedevries.nl/en/blog/2018-01-13-making-password-managers-play-ball-with-your-login-form)

Thanks for your reply,
Lars

**Comment by hillelcoren** [comment]
Hi,

This should sort of already work, you may not see the option in the field but you should be able to fill the form by clicking the plugin icon in the toolbar.

**Comment by LarsK1** [comment]
It does work, if you manually force the password-manager to fill the fields. For me it seems, it isn't recognized, because it's no just a single form but at least 2?

**Comment by hillelcoren** [comment]
The app is built with [Flutter](https://flutter.dev/), all apps (web/mobile/desktop) are compiled from one shard codebase. 

We'll most likely need to wait for this to be corrected in the framework, here's one related issue but there are more: https://github.com/flutter/flutter/issues/81201

**Comment by kevmoo** [comment]
The fix for this has landed and will be in the next stable Flutter release!

**Comment by hillelcoren** [comment]
If you have a chance please check if there's a difference with the latest release

**Comment by LarsK1** [comment]
Hi @hillelcoren ,
the password and 2FA fields are now detected. The user field is still missing the autocomplete="username" field (currently it's autocomplete="").

But it's still not perfect, since it seems, that the html for the input fields is generated on the flow, so that the password managers can only fill one field at a time.

**Comment by htoor3** [comment]
@LarsK1 the inputs are lazy-loaded which can lead to some issues with password manager autofill (being tracked [here](https://github.com/flutter/flutter/issues/127694)). 

To fix your second issue re: `autocomplete` attribute, make sure you're wrapping your text fields in an `AutofillGroup` and make sure to pass the appropriate autofill hints to the text field.  In your case, it would be `autofillHints: [AutofillHints.username]`.  I tried this on my end and it's populating the correct `autocomplete` attribute for the input.

**Comment by LarsK1** [comment]
@htoor3 yes it's only filling the field I currently selected. If none is selected none is filled.
The password manager used is Roboform.

For the rest @hillelcoren would you mind checking - I'm not really into Flutter 😞
